# Generated by Django 5.0 on 2026-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("system", "系统通知"),
                            ("audit", "审核通知"),
                            ("important", "重要通知"),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="公告分类",
                    ),
                ),
                (
                    "is_top",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否置顶"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否有效"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生效时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="失效时间"
                    ),
                ),
                (
                    "publisher_name",
                    models.CharField(max_length=100, verbose_name="发布人姓名"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="查看次数")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "db_table": "announcement",
                "ordering": ["-is_top", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="材料类型"
                    ),
                ),
                (
                    "material_id",
                    models.BigIntegerField(db_index=True, verbose_name="材料ID"),
                ),
                (
                    "auditor_name",
                    models.CharField(max_length=100, verbose_name="审核人姓名"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("approved", "通过"), ("rejected", "驳回")],
                        db_index=True,
                        max_length=20,
                        verbose_name="审核结果",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="审核意见"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="审核时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "审核记录",
                "verbose_name_plural": "审核记录",
                "db_table": "audit_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="消息标题")),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("audit_result", "审核结果"), ("system", "系统消息")],
                        db_index=True,
                        max_length=50,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已读"
                    ),
                ),
                (
                    "related_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="关联类型"
                    ),
                ),
                (
                    "related_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "db_table": "message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="操作用户姓名",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="操作类型"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="操作模块"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="操作内容"),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="用户代理"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "operation_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity",
                    models.CharField(
                        choices=[("graduate", "研究生"), ("undergraduate", "本科生")],
                        db_index=True,
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="模块名称"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "权限配置",
                "verbose_name_plural": "权限配置",
                "db_table": "permission_config",
            },
        ),
    ]
