# Generated by Django 5.0 on 2026-01-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布人",
            ),
        ),
        migrations.AddField(
            model_name="auditrecord",
            name="auditor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收用户",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作用户",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionconfig",
            index=models.Index(
                fields=["identity", "module"], name="permission__identit_2ab50c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permissionconfig",
            unique_together={("identity", "module")},
        ),
        migrations.AddIndex(
            model_name="auditrecord",
            index=models.Index(
                fields=["material_type", "material_id"],
                name="audit_recor_materia_d3af3c_idx",
            ),
        ),
    ]
