# Generated by Django 5.0 on 2026-01-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="permissionconfig",
            name="permission__identit_2ab50c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="permissionconfig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="permissionconfig",
            name="material_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("research_project", "课题项目"),
                    ("monograph", "专著"),
                    ("paper", "论文"),
                    ("other_academic", "其他学术成果"),
                    ("technology_competition", "科技竞赛"),
                    ("social_practice", "社会实践调研"),
                    ("social_service", "服务社会"),
                    ("other_practice", "其他实践活动"),
                ],
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="材料类型",
            ),
        ),
        migrations.AlterField(
            model_name="permissionconfig",
            name="module",
            field=models.CharField(
                choices=[
                    ("dashboard", "首页"),
                    ("materials", "我的材料"),
                    ("academic", "学术成果"),
                    ("practice", "服务与实践"),
                    ("statistics", "数据统计"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="模块名称",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permissionconfig",
            unique_together={("identity", "module", "material_type")},
        ),
        migrations.AddIndex(
            model_name="permissionconfig",
            index=models.Index(
                fields=["identity", "module", "material_type"],
                name="permission__identit_5f47c2_idx",
            ),
        ),
    ]
