# Generated by Django 5.0 on 2026-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小（字节）")),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="文件类型"
                    ),
                ),
                (
                    "file_ext",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="文件扩展名"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="材料类型"
                    ),
                ),
                (
                    "material_id",
                    models.BigIntegerField(db_index=True, verbose_name="材料ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "文件",
                "verbose_name_plural": "文件",
                "db_table": "file",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Monograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("teacher", "老师"),
                            ("graduate", "研究生"),
                            ("undergraduate", "本科生"),
                        ],
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("auditing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="专著名称")),
                (
                    "publish",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="出版社"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="出版时间"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="编号"
                    ),
                ),
                (
                    "supervisor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="导师姓名"
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(blank=True, null=True, verbose_name="撰写字数"),
                ),
                (
                    "author",
                    models.TextField(blank=True, null=True, verbose_name="作者及顺序"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "专著",
                "verbose_name_plural": "专著",
                "db_table": "monograph",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OtherAcademic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("teacher", "老师"),
                            ("graduate", "研究生"),
                            ("undergraduate", "本科生"),
                        ],
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("auditing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="富文本内容"),
                ),
            ],
            options={
                "verbose_name": "其他学术成果",
                "verbose_name_plural": "其他学术成果",
                "db_table": "other_academic",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OtherPractice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("teacher", "老师"),
                            ("graduate", "研究生"),
                            ("undergraduate", "本科生"),
                        ],
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("auditing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="级别"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="时间")),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="提供证明单位",
                    ),
                ),
                (
                    "author",
                    models.TextField(blank=True, null=True, verbose_name="参与人"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "其他实践活动",
                "verbose_name_plural": "其他实践活动",
                "db_table": "other_practice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("teacher", "老师"),
                            ("graduate", "研究生"),
                            ("undergraduate", "本科生"),
                        ],
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("auditing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="论文题目")),
                (
                    "publication",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="刊物名称"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="类别"
                    ),
                ),
                (
                    "publication_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="刊号"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="发表时间"
                    ),
                ),
                (
                    "journal_status",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="期刊收录情况",
                    ),
                ),
                (
                    "partition",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="中科院分区"
                    ),
                ),
                (
                    "supervisor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="导师姓名"
                    ),
                ),
                (
                    "first_unit",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否第一单位"
                    ),
                ),
                (
                    "communication",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="导师是否通讯"
                    ),
                ),
                (
                    "author",
                    models.TextField(blank=True, null=True, verbose_name="作者及排名"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "论文",
                "verbose_name_plural": "论文",
                "db_table": "paper",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("teacher", "老师"),
                            ("graduate", "研究生"),
                            ("undergraduate", "本科生"),
                        ],
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("auditing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="项目名称"),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="项目级别"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="立项时间"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结题时间"),
                ),
                (
                    "funds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="项目经费（万元）",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="项目编号"
                    ),
                ),
                (
                    "personnel",
                    models.TextField(
                        blank=True, null=True, verbose_name="主持人、参与人员及顺序"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "课题项目",
                "verbose_name_plural": "课题项目",
                "db_table": "research_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialPractice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("teacher", "老师"),
                            ("graduate", "研究生"),
                            ("undergraduate", "本科生"),
                        ],
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("auditing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="级别"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="时间")),
                (
                    "author",
                    models.TextField(
                        blank=True, null=True, verbose_name="主持人、参与者、顺序"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "社会实践调研",
                "verbose_name_plural": "社会实践调研",
                "db_table": "social_practice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("teacher", "老师"),
                            ("graduate", "研究生"),
                            ("undergraduate", "本科生"),
                        ],
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("auditing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="级别"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="时间")),
                (
                    "author",
                    models.TextField(blank=True, null=True, verbose_name="作者及顺序"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "服务社会",
                "verbose_name_plural": "服务社会",
                "db_table": "social_service",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyCompetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=50, verbose_name="学号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("teacher", "老师"),
                            ("graduate", "研究生"),
                            ("undergraduate", "本科生"),
                        ],
                        max_length=20,
                        verbose_name="身份",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("auditing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("withdrawn", "已撤回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "competition",
                    models.CharField(max_length=200, verbose_name="赛事名称"),
                ),
                (
                    "is_whitelist",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否为白名单赛事"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="作品名称"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("school", "校级"),
                            ("college", "院级"),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="级别",
                    ),
                ),
                (
                    "award_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="获奖时间"
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="获奖等级"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="组织单位名称",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="团体/个人"
                    ),
                ),
                (
                    "author",
                    models.TextField(
                        blank=True, null=True, verbose_name="负责人/参与者及顺序"
                    ),
                ),
                (
                    "supervisor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="指导老师"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "科技竞赛",
                "verbose_name_plural": "科技竞赛",
                "db_table": "technology_competition",
                "ordering": ["-created_at"],
            },
        ),
    ]
