# Generated by Django 5.0 on 2026-01-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="upload_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传用户",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["material_type", "material_id"], name="file_materia_b2a013_idx"
            ),
        ),
    ]
